# Generated by Django 3.0.6 on 2020-05-10 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=45)),
                ('commodity', models.CharField(max_length=45)),
                ('description', models.TextField(editable=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAds',
            fields=[
                ('ads_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Ads_content', models.ImageField(max_length=256, upload_to=None)),
                ('activity', models.CharField(max_length=256)),
                ('Ads_title', models.CharField(max_length=256)),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Category', verbose_name='category')),
                ('pricing_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Pricing', verbose_name='pricing')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_names', models.CharField(max_length=45)),
                ('user_type', models.BooleanField()),
                ('activity', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=45)),
                ('phone_number', models.CharField(default='+254700000000', max_length=15)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviews_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField()),
                ('review_message', models.TextField(editable=False)),
                ('date', models.DateField(auto_now=True)),
                ('ads_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.ProductsAds', verbose_name='ads')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Users', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='productsads',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Users', verbose_name='users'),
        ),
    ]
