# Generated by Django 3.0.6 on 2020-05-11 15:32
# pylint: skip-file


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('farmzone_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmzoneuser',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Location'),
        ),
    ]
