# Generated by Django 3.0.6 on 2020-05-11 16:48
# pylint: skip-file

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmzone_users', '0002_farmzoneuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmzoneuser',
            old_name='Location',
            new_name='location',
        ),
    ]
